language: c
addons:
  apt_packages:
    - make
    - git
    - groff
    - ncurses-dev
  homebrew:
    packages:
      - make
      - git
      - groff
      - ncurses
branches:
 - moraes
os:
 - linux
 - osx
compiler:
 - gcc
 - clang
arch:
 - amd64
 - arm64
 - ppc64le
 - s390x
script:
 - u=$(uname); case $u in Linux) make SYSDEFS=-DXLINUX TERMCAPLIB=-lncurses; make clean; make SYSDEFS='-DBAREBONES -DJTC'; make clean; make SYSDEFS='-DPIPEPROCS -DPOSIX_PROCS';; Darwin) make SYSDEFS=-DXBSD TERMCAPLIB=-lncurses;; *) echo "Unknown uname \"$u\"";; esac
